version: '3.8'
services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_gateway
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    networks:
      - resource_management_network
    environment:
      - AUTH_SERVICE_URL=http://auth_service:8000
      - BOOKING_SERVICE_URL=http://booking_service:8000
      - RESOURCE_SERVICE_URL=http://resource_service:8000
      - NOTIFICATION_SERVICE_URL=http://notification_service:8000
      - REPORT_SERVICE_URL=http://report_service:8000

networks:
  resource_management_network:
    external: true