version: '3.8'

#NETWORKS
networks:
  foe_rbs_network:
    driver: bridge

#SERVICES
services:

  #POSTGRESQL DATABASES (One for each service with data)
  db_auth:
    image: postgres:15-alpine
    container_name: foe_rbs_db_auth
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - auth_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - foe_rbs_network

  db_resource:
    image: postgres:15-alpine
    container_name: foe_rbs_db_resource
    environment:
      POSTGRES_DB: resource_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - resource_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - foe_rbs_network

  db_booking:
    image: postgres:15-alpine
    container_name: foe_rbs_db_booking
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - booking_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - foe_rbs_network


  #API GATEWAY (Fixed to use Laravel Artisan Serve)
  api_gateway:
    build:
      context: ./api-gateway/
      dockerfile: Dockerfile
    container_name: foe_rbs_api_gateway
    volumes:
      - ./api-gateway:/var/www/html
    ports:
      - "8000:80"
    networks:
      - foe_rbs_network
    depends_on:
      - db_auth
      - auth_service
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile.dev
    container_name: foe_rbs_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - foe_rbs_network
    environment:
      VITE_API_BASE_URL: http://localhost:8000/api
    restart: unless-stopped


  #MICROSERVICES (The backend logic - PHP-FPM containers)
  auth_service:
    build:
      context: ./services/auth_service/
      dockerfile: Dockerfile
    container_name: foe_rbs_auth_service
    volumes:
      - ./services/auth_service:/var/www/html
    ports:
      - "8001:80"
    environment:
      DB_HOST: db_auth
      DB_PORT: 5432
      DB_DATABASE: auth_db
    networks:
      - foe_rbs_network
    depends_on:
      - db_auth
    restart: unless-stopped

  booking_service:
    build:
      context: ./services/booking_service/
      dockerfile: Dockerfile
    container_name: foe_rbs_booking_service
    volumes:
      - ./services/booking_service:/var/www/html
    environment:
      DB_HOST: db_booking
      DB_PORT: 5432
      DB_DATABASE: booking_db
    networks:
      - foe_rbs_network
    depends_on:
      - db_booking
    restart: unless-stopped

  resource_service:
    build:
      context: ./services/resource_service/
      dockerfile: Dockerfile
    container_name: foe_rbs_resource_service
    volumes:
      - ./services/resource_service:/var/www/html
    environment:
      DB_HOST: db_resource
      DB_PORT: 5432
      DB_DATABASE: resource_db
    networks:
      - foe_rbs_network
    depends_on:
      - db_resource
    restart: unless-stopped

#VOLUMES (Data Persistence)
volumes:
  auth_data:
  resource_data:
  booking_data: